#! /usr/bin/env bash
set +x

# This script iterates through each spec file and tries to cross compiler and
# run it on wasm32 platform.
#
# * `failed codegen` annotates specs that error in the compiler.
#   This is mostly caused by some API not being ported to win32 (either the spec
#   target itself or some tools used by the spec).
# * `failed linking` annotats specs that compile but don't link (at least not on
#   basis of the libraries from *Porting to WASM* guide).
#   Most failers are caused by missing libraries (libxml2, libyaml, libgmp,
#   libllvm, libz, libssl), but there also seem to be some incompatibilities
#   with the existing libraries.
# * `failed to run` annotates specs that compile and link but don't properly
#   execute.
#
# PREREQUISITES:
#
# This script requires a working wasm32 build environment as described in
# the [*Porting to WASM* guide](#TODO)
#
# * RUNNER points to a WASM runtime program that executes the compiled binary.
#
# The defaults requires WASI_SDK_PATH to be set appropriately.
#
# USAGE:
#
# For std spec:
# $ spec/generate_wasm_spec.sh > spec/wasm32_std_spec.cr
# For compiler spec:
# $ spec/generate_wasm_spec.sh compiler > spec/wasm32_compiler_spec.cr

SPEC_SUITE=${1:-std}
RUNNER=${RUNNER:-wasmtime run --enable-memory}
CRYSTAL_LIBRARY_PATH=${CRYSTAL_LIBRARY_PATH:-"$HOME/toolchains/crystal-wasm-libs/targets/wasm32-wasi"}
WASI_SDK_PATH=${WASI_SDK_PATH:-"$HOME/toolchains/wasi-sdk-9.0"}

if [ "$LINKER" == "crystal-windows-wsl" ] && [ -z "$WASI_SDK_PATH" ]; then
  echo "Missing environment variable MSVC_BUILD_TOOLS" >&2
  exit 1
fi

export CC="$WASI_SDK_PATH/bin/clang --sysroot=$WASI_SDK_PATH/share/wasi-sysroot"
export LIBRARY_PATH="$WASI_SDK_PATH/share/wasi-sysroot/lib/wasm32-wasi"

if [ -f "bin/crystal" ]; then
  CRYSTAL_BIN=${CRYSTAL_BIN:-bin/crystal}
else
  CRYSTAL_BIN=${CRYSTAL_BIN:-crystal}
fi

command="$0 $*"
echo "# This file is autogenerated by \`${command% }\`"
echo "# $(gdate --rfc-3339 seconds)"
echo

for spec in $(find "spec/$SPEC_SUITE" -type f -iname "*_spec.cr" | sort); do
  require="require \"./${spec##spec/}\""

  if ! linker_command=$($CRYSTAL_BIN build --cross-compile --target wasm32-wasi --static -Dgc_none -Dwithout_zlib -Dwithout_openssl --error-trace "$spec"); then
    echo "# $require (failed codegen)"
    continue
  fi

  if ! eval $linker_command >/dev/null 2>/dev/null; then
    echo "# $require (failed linking)"
    continue
  fi

  binary_path="./$(echo "$linker_command" | ggrep -oP '(?<="/Fe)(.*)(?=")').exe"

  $RUNNER "$binary_path" > /dev/null; exit=$?

  if [ $exit -eq 0 ] || [ $exit -eq 1 ]; then
    echo "$require"
  else
    echo "# $require (failed to run)"
  fi
done
